My_Django_Stuff/advanced_section/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basicapp/', include('basicapp.urls', namespace='basicapp')),
]

My_Django_Stuff/advanced_section/advcbv/basicapp/urls.py
from django.urls import path, include
#from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    #url(r'^(?P<pk>[-\w]+)/$', views.SchoolDetailView.as_view(),name='detail'),
    path('<int:pk>/', views.SchoolDetailView.as_view(),name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name = 'create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name = 'delete'),
]

My_Django_Stuff/advanced_section/advcbv/basicapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basicapp:detail", kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

My_Django_Stuff/advanced_section/advcbv/basicapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from . import models

# Create your views here.
# class CBView(View):
#     def get(self,request):
#         return HttpResponse("Class based views are cool!")

class IndexView(TemplateView):
    template_name = 'index.html'

#
#     #kwargs means key word arguments
#     def get_context_data(self,**kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = 'BASIC INJECTION!'
#         return context
#

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basicapp/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basicapp:list")
    

My_Django_Stuff/advanced_section/advcbv/basicapp/templates/basicapp/basicapp_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basicapp:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li></li>

      </ul>

    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>


  </body>
</html>

My_Django_Stuff/advanced_section/advcbv/basicapp/templates/basicapp/school_confirm_delete.html
{% extends "basicapp/basicapp_base.html" %}

{% block body_block %}
<h1>Delete {{school.name}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basicapp:detail' pk=school.pk %}">Cancel</a>

</form>

{% endblock %}

My_Django_Stuff/advanced_section/advcbv/basicapp/templates/basicapp/school_detail.html
{% extends "basicapp/basicapp_base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the School Detail Page</h1>
  <h2>School Details: </h2>
  <p>Name: {{ school_detail.name }}</p>
  <p>Principal: {{ school_detail.principal }}</p>
  <p>Location: {{ school_detail.location }}</p>
  <h3>Students: </h3>

  {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old</p>
  {% endfor %}

</div>

<div class="container">
  <p><a class="btn btn-warning" href="{% url 'basicapp:update' pk=school_detail.pk %}">Update</a></p>
  <p><a class="btn btn-danger" href="{% url 'basicapp:delete' pk=school_detail.pk %}">Delete</a></p>

</div>

{% endblock %}

My_Django_Stuff/advanced_section/advcbv/basicapp/templates/basicapp/school_form.html
{% extends "basicapp/basicapp_base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>

<form  method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="btn btn-primary" value="Submit">

</form>

{% endblock %}

My_Django_Stuff/advanced_section/advcbv/basicapp/templates/basicapp/school_list.html
{% extends "basicapp/basicapp_base.html" %}

{% block body_block %}
<h1>Welcome to a list of all the school!</h1>
<ol>
  {% for school in schools %}
  <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
  {% endfor %}
</ol>

<p><a class="btn btn-primary" href="{% url 'basicapp:create' %}">Create School</a></p>
{% endblock %}